### ISSUE TITLE
Calendar not showing when logged in.

### ISSUE THREAD

**Issue by mzzy21** [EchoLeague/Echo-League-Website-Testing#1]
Couldn't see the 'Calendar' tab on the pullout menu when logged into my account. Tried hard-refresh, closing tab and reopening, on mobile and in another browser (originally on chrome, tested on internet explorer).

![](https://i.gyazo.com/dbf58084919b6fe709aa35647d771e4a.png)

**Comment by Lancerskypro** [comment]
same problem on chrome

**Comment by ammuench** [comment]
Oops, looks like we need to update this to show it on logged-in user, haha

**Comment by ammuench** [comment]
Updatd in 0.15.3
