### ISSUE TITLE
Bug with users who have Teams set as 'No Team'

### ISSUE THREAD

**Issue by tejas-mishra** [EchoLeague/Echo-League-Website-Testing#10]
Initial page of user with no team
![scr1](https://cloud.githubusercontent.com/assets/19583775/22094271/4b71e3aa-ddda-11e6-8fbb-4f42b4698909.PNG)
I click on the team page, and it takes me to 
![scr2](https://cloud.githubusercontent.com/assets/19583775/22094292/779081d0-ddda-11e6-9e8d-fe3d2575cd21.PNG)
When I click back once 
![scr3](https://cloud.githubusercontent.com/assets/19583775/22094315/9093cda4-ddda-11e6-8be2-db1a2c8a32b4.PNG)
I need to click back once more to go back to the page in the first screenshot.
Its not really site-breaking...but whatever.

**Comment by ammuench** [comment]
should be fixed with front end v 0.15.2
