### ISSUE TITLE
Text Discrepancy between /rules and /register on requiring solo mmr ranking

### ISSUE THREAD

**Issue by genjek** [EchoLeague/Echo-League-Website-Testing#11]
/Register says calibrated solo mmr is required to participate; /rules says it isn’t required and can be subject to review of other match data, in the event that your MMR is not available due to not playing enough ranked games.

If /rules is up to date in this case, make sure a system is in place to flag the account registering for review if solo mmr is not available (or however you want to implement it).  If this is already a thing then I apologize,  just need to fix the inconsistencies in the text.

**Comment by ammuench** [comment]
`/rules` is actually out of date, and using old copy.  Assume the rules hosted here: https://github.com/EchoLeague/Echo-League-Rules to be the official ruleset.  

We will update the site by our launch date though. Thank you :)
