### ISSUE TITLE
Opening a player page is weird

### ISSUE THREAD

**Issue by tejas-mishra** [EchoLeague/Echo-League-Website-Testing#14]
I try to open u/d's profile
![player_ex_1](https://cloud.githubusercontent.com/assets/19583775/22094923/0c886dd0-dddf-11e6-89a8-0d89668945b5.PNG)
If you look at the top left corner, the back button is open, when infact I opened a new tab
![image](https://cloud.githubusercontent.com/assets/19583775/22094946/3126ebee-dddf-11e6-8c6d-453237e134d9.png)
This is where it took me after I clicked the back button
![player_ex_3](https://cloud.githubusercontent.com/assets/19583775/22094964/50fcdb04-dddf-11e6-9d26-b244c164975c.PNG)

**Comment by ammuench** [comment]
So this is an issue with Angular2 itself.  Since it's non breaking i don't think we can do much to fix this.
