### ISSUE TITLE
Improve visibility of "edit" icon on /profile

### ISSUE THREAD

**Issue by genjek** [EchoLeague/Echo-League-Website-Testing#16]
After Met didn't notice the edit icon currently down in the bottom right of the page, thought you might want to move the icon to a more visible location. 

My suggestion is moving "edit" icon to the blue profile name box.  That's kind of how it is in dota/steam profiles anyways, consistency doesn't hurt, it should make it a more intuitive place to look for people wanting to edit their profiles.

**Comment by ammuench** [comment]
We're sticking with current Material Design standards for this.  I think we'll keep it at this as is for the time being, but might look into adjusting layouts for S1
