### ISSUE TITLE
Profile fields can't have unicode characters above U+00FF

### ISSUE THREAD

**Issue by liampwll** [EchoLeague/Echo-League-Website-Testing#19]
**Browser:** Chrome Version 55.0.2883.87 (64-bit)

**User State:** Logged In

**Environment:** Test Server

**Version or Branch:** 0.15.1

**Description:** When unicode characters above U+00FF such as 'Ā' are put in any field on a users profile it will show a '?'

**Steps to Reproduce:**

1. Edit any field on your profile to contain a unicode character above U+00FF such as 'Ā'
2. Save profile and reload page

**Comment by ammuench** [comment]
Known issue with mySQL, users will be restricted to UTF8
