### ISSUE TITLE
Inconsistent spacing on user profiles

### ISSUE THREAD

**Issue by liampwll** [EchoLeague/Echo-League-Website-Testing#20]
**Browser:** Chrome Version 55.0.2883.87 (64-bit)

**User State:** Logged In

**Environment:** Test Server

**Version or Branch:** 0.15.1

**Description:** The space between User Bio and Regions is not the same as the space between Regions and Availability

**Screenshots:** https://i.imgur.com/DVGmpFm.png

**Comment by ammuench** [comment]
Will update in future release
