### ISSUE TITLE
Players can join any team without being added by captain

### ISSUE THREAD

**Issue by liampwll** [EchoLeague/Echo-League-Website-Testing#26]
**User State:** Logged In

**Environment:** Test Server

**Version or Branch:** 0.15.1

**Description:** Players can join any team they want by modifying the PUT request when editing their profile.

**Steps to Reproduce:**

1. Edit profile and intercept PUT request
2. Change `"team_id"` to a team ID

**Comment by ammuench** [comment]
fixed with backend version 0.13.2
