### ISSUE TITLE
Users can edit any team's profile

### ISSUE THREAD

**Issue by liampwll** [EchoLeague/Echo-League-Website-Testing#29]
**User State:** Logged In

**Environment:** Test Server

**Version or Branch:** 0.15.1

**Description:** Users can edit any team they want by modifying the PUT request when editing their teams profile.

**Steps to Reproduce:**

1. Edit team profile and intercept PUT request
2. Change `"id"` to a different team ID

**Comment by ammuench** [comment]
Fixed in Aftershock 0.13.2, deploying shortly
