### ISSUE TITLE
When showing servers on 'Free Agent' tab it shows Oceania as 'OCN_Rigid OCN_Flex' 

### ISSUE THREAD

**Issue by mzzy21** [EchoLeague/Echo-League-Website-Testing#30]
**Browser(s):** Chrome

**User state:** Logged in

**Enviroment:** Test Server

**Version or Branch:** 0.15.1

**Description:** When checked box for playable servers 'Oceania' in the 'Free Agents' tab it shows as 'OCN_Rigid OCN_Flex' as opposed to the abbreviation OCN like Europe West to EUW.

**Screenshot(s):** 

![](https://i.gyazo.com/f398709c3e6b5e0378d16aeb6155383a.png)

Also as a sidenote a comma would be nice to separate the information in the 'Free Agents' tab

**Comment by ammuench** [comment]
We'll be getting rid of the OCN Rigid/Flex distinction
