### ISSUE TITLE
Team edit view changes size of overhead box + foreign language to question marks

### ISSUE THREAD

**Issue by mzzy21** [EchoLeague/Echo-League-Website-Testing#31]
**Browser(s):** Chrome

**User state:** Logged in

**Enviroment:** Test Server

**Version or Branch:** 0.15.1

**Description:** When I enter the team edit view as Organiser the overhead blue box gets bigger and the picture fits, is this intentional and is the team name supposed to go there?

Additionally, the Japanese letters in the team bio were automatically changed to question marks after refreshing

**Screenshots:** 

![](https://i.gyazo.com/578a884dd827b49f79a0ffdbb4bdc11b.png)

![](https://i.gyazo.com/e14820f70c6f56ef753e69fda626c60e.png)

**Comment by ammuench** [comment]
Empty name is fixed in 0.13.5 of backend service.

Characters will be restricted to UTF8 charset
