### ISSUE TITLE
All players email's and registration ip's and returned from http://test.echoleague.gg:8081/user/getAll

### ISSUE THREAD

**Issue by liampwll** [EchoLeague/Echo-League-Website-Testing#32]
**User State:** Logged In

**Environment:** Test Server

**Version or Branch:** 0.15.1

**Description:** All players email's and registration ip's and returned from http://test.echoleague.gg:8081/user/getAll

**Steps to Reproduce:**

1. Go to http://test.echoleague.gg:8081/user/getAll

**Comment by ammuench** [comment]
Fixed in backend version 0.13.3
