### ISSUE TITLE
User can break profile and free agents list by editing PUT request when editing profile

### ISSUE THREAD

**Issue by liampwll** [EchoLeague/Echo-League-Website-Testing#33]
**User State:** Logged In

**Environment:** Test Server

**Version or Branch:** 0.15.6

**Description:** User can break profile and free agents list by editing PUT request when editing profile

**Steps to Reproduce:**

1. Edit profile
2. Intercept `PUT http://test.echoleague.gg:8081/user/put/xxxxxxxxxxxx` request
3. Edit to only contain ID and timezone, for example `{"id":"76561198053315971","timezone":"SGT"}`

**Comment by ammuench** [comment]
Fixed in backend v0.13.6
