### ISSUE TITLE
User can add arbitrary strings as regions when editing profile

### ISSUE THREAD

**Issue by liampwll** [EchoLeague/Echo-League-Website-Testing#36]
**User State:** Logged In

**Environment:** Test Server

**Version or Branch:** 0.15.6

**Description:** User can add arbitrary strings as regions when editing profile

**Steps to Reproduce:**

1. Intercept `PUT http://test.echoleague.gg:8081/user/put/<ID>` request
2. Change `"region"` to something like this `"region":{"USE":9,"USW":9,"EUW":0,"SEA":-1,"You're":true,"still":true,"not":true,"checking":true,"enough":true,"stuff":true,"on":true,"profile":true,"edits":true}`

**Comment by ammuench** [comment]
Added checks for this in v0.15.12
