### ISSUE TITLE
User can add arbitrary strings as roles during registration

### ISSUE THREAD

**Issue by liampwll** [EchoLeague/Echo-League-Website-Testing#37]
**User State:** Logged In

**Environment:** Test Server

**Version or Branch:** 0.15.6

**Description:** User can add arbitrary strings as roles during registration

**Steps to Reproduce:**

1. Intercept `POST http://test.echoleague.gg:8081/user/create`
2. Change `"roles"` to something else, for example `"roles":{"pos1":true,"pos2":true,"pos3":true,"pos4":false,"pos9":true,"random":true,"words":true,"in":true,"roles":true}`

**Comment by ammuench** [comment]
Added checks for this in v0.15.12
