### ISSUE TITLE
Clicking anything in the sidebar after registration will leave the success message on the page

### ISSUE THREAD

**Issue by liampwll** [EchoLeague/Echo-League-Website-Testing#38]
**Browser:** Chrome

**User State:** Logged In

**Environment:** Test Server

**Version or Branch:** 0.15.6

**Description:** Clicking anything in the sidebar after registration will leave the success message on the page

**Steps to Reproduce:**

1. Register and don't click the go home button
2. Click anything in the sidebar

**Screenshots:** https://i.imgur.com/XAKEeqO.png

**Comment by ammuench** [comment]
Fixed in 0.15.11
