### ISSUE TITLE
Getting error when trying to submit team profile changes

### ISSUE THREAD

**Issue by Tornadospeed** [EchoLeague/Echo-League-Website-Testing#5]
**Browser:** Chrome

**User State:** Logged in

**Environment:** Test Server

**Version or Branch:** 0.15.1

**Description:** Getting: "Error 500: Error sending data to database, please try again
Contact an admin if this error keeps occuring"

**Steps to Reproduce:**

1. Go to team page
2. Edit team information
3. click the big green check

**Screenshots:** 
http://i.imgur.com/KWpX9Bw.png
http://i.imgur.com/2WcgG4w.png

**Add'l Info:** N/A

**Comment by Quazia** [comment]
This error should be resolved shortly. Thanks for bringing this to our attention.
