### ISSUE TITLE
The schedule accepts strings.

### ISSUE THREAD

**Issue by tejas-mishra** [EchoLeague/Echo-League-Website-Testing#6]
![timezoneissue](https://cloud.githubusercontent.com/assets/19583775/22093781/882fd238-ddd6-11e6-82e4-95ae6f22defd.PNG)
Shouldn't it just be time like AM/PM ?

**Comment by genjek** [comment]
Idk, strings allows players to share more details for effective manual scheduling.  But if you want to make a tool to help automatically figure out schedules (at least to a general time of day) then a standardized method of entry would be better.

**Comment by ammuench** [comment]
This is working as intended
