### ISSUE TITLE
Team tab in sidebar is bugged

### ISSUE THREAD

**Issue by tejas-mishra** [EchoLeague/Echo-League-Website-Testing#7]
There should be two tabs , one should be Team for our own team, second should be Teams for the rest of the teams in the league. I see only one and that seems bugged.
![team_tab](https://cloud.githubusercontent.com/assets/19583775/22094034/72a20ace-ddd8-11e6-9ee1-9216e1e2fecf.PNG)

**Comment by ammuench** [comment]
Fixed in 0.15.4
